BestDeals/urls.py
from django.urls import path
from .views import best_deals, add_to_deals, edit_deals, delete_deals, show_json  # Import the view

app_name = 'BestDeals'

urlpatterns = [
    path('', best_deals, name='best_deals'),  # URL for best deals
    path('add-to-deals/', add_to_deals, name='add_to_deals'),
    path('edit-deals/<uuid:product_id>/', edit_deals, name='edit_deals'),
    path('delete-deals/<uuid:product_id>/', delete_deals, name='delete_deals'),
    path('json/', show_json, name='show_json'),
]

Discussions/urls.py
from django.urls import path
from .views import create_thread, add_comment, view_threads

app_name = 'Discussions'

urlpatterns = [
    path('create_thread/', create_thread, name='create_thread'),
    path('add_comment/<int:thread_id>/', add_comment, name='add_comment'),
    path('view_threads/', view_threads, name='view_threads'),
]

SoundNest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('wishlist/', include('WishList.urls')),
    path('', include('products.urls')),
    path('reviews/', include('reviews.urls')),
    path('discussion/', include('Discussions.urls')),
    path('best-deals/', include('BestDeals.urls')),
    #dwada
]

WishList/urls.py
from django.urls import path
from WishList.views import *


app_name = 'WishList'


urlpatterns = [
    path('view_wishlist', view_wishlist, name='view_wishlist'),
    path('json/product', get_product_json, name='get_product_json'),
    path('json/wishlist', get_wishlist_json, name='get_wishlist_json'),
    path('json/<str:id>/', get_product_json_by_id, name='get_product_json_by_id'),
    path('add-product-entry-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('delete/<int:id>/', delete_wish, name='delete_wish'),
    path('create-wishlist-flutter/', create_wishlist_flutter, name='create_wishlist_flutter'),
    path('delete_flutter/', delete_flutter, name='delete_flutter'),
    path('edit_quantity_flutter/', edit_quantity_flutter, name='edit_quantity_flutter'),
    #path('home/', home, name='home'),
    #path('login/', login_user, name='login'),
    #path('register/', register_user, name='register'),
    #path('logout/', logout_user, name='logout'),
]

products/urls.py
from django.urls import path
from products.views import *

app_name = 'products'

urlpatterns = [
    path('api/products/', get_products, name='get_products'),
    path('', show_product, name='home'),
    path('details/<uuid:product_id>/', product_details, name='product_details'),
    path('add_product/', add_product, name='add_product'),
    path('delete_product/', delete_product, name='delete_product'), 
    path('details/json/<uuid:product_id>/', product_details_json, name='product_details_json'),
    path('edit_product', edit_product, name='edit_product'),
    path('create_flutter/', create_product_flutter, name='create_product_flutter'),
    path('edit_flutter/<str:product_id>/', edit_product_flutter, name='edit_product_flutter'),
    path('delete_flutter/<str:product_id>/', delete_product_flutter, name='delete_product_flutter'),
]

reviews/urls.py
from django.urls import path
from reviews.views import *

app_name = 'reviews'

urlpatterns = [
    path('show_reviews', show_reviews, name='show_reviews'),
    path('add/', add_review, name='add_review'),
    path('edit/<uuid:review_id>/', edit_review, name='edit_review'),
    path('delete/<uuid:review_id>/', delete_review, name='delete_review'),
    path('api/', review_list, name='review_list'),
    path('flutter/show_reviews/', show_reviews_flutter, name='show_reviews_flutter'),
    # path('user_reviews/', get_user_reviews, name='get_user_reviews'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block meta %}{% endblock meta %}
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
    </head>
    
    {% include 'navbar.html' %}
    <body>
        {% block content %}{% endblock content %}
    </body>
    {% include 'footer.html' %}
</html>

templates/footer.html
{% load static %}

<footer class="py-8">
    <div class="container mx-auto px-8 sm:px-6 lg:px-16 mt-6">
        <div class="flex flex-col md:flex-row justify-between items-start">
            <div class="footer-left">
                <h2 class="text-2xl font-bold">Soundnest</h2>
                <p class="mt-6 mb-10 text-gray-400 font-semibold">
                    Fakultas Ilmu Komputer Universitas Indonesia<br>
                    Depok, West Java<br>
                    Indonesia
                </p>
            </div>
            <div class="footer-right mb-8 md:mt-0 md:text-left">
                <ul class="flex flex-col space-y-8 font-semibold mr-8">
                    <li><a href="#" class="hover:text-gray-400">Home</a></li>
                    <li><a href="{% url 'products:home' %}" class="hover:text-gray-400">Products</a></li>
                    <li><a href="{% url 'Discussions:view_threads' %}" class="hover:text-gray-400">Discussions</a></li>
                </ul>
            </div>
        </div>
        <hr class="my-4 border-gray-300"> <!-- Grey line -->
        <p class="font-semibold mt-6 text-gray-600">&copy; 2024 Soundnest. All rights reserved.</p>
    </div>
</footer>

templates/navbar.html
{% load static %}
<nav class="border-b border-gray-300 bg-white h-25">
    <div class="max-w-screen mx-auto py-4 px-6 md:px-12 h-full">
        <div class="flex justify-between items-center h-full">
            <a href="{% url 'BestDeals:best_deals' %}" class="flex items-center font-bold">
                <img src="{% static 'images/logo.webp' %}" alt="Soundnest Logo" class="h-10 w-auto mr-1">
                SOUNDNEST
            </a>

            <!-- Hamburger Icon (Mobile) -->
            <div class="md:hidden flex">
                <button id="mobileMenuButton" class="focus:outline-none">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" />
                    </svg>
                </button>
            </div>

            <!-- Desktop Menu -->
            <ul class="hidden md:flex items-center justify-center flex-grow space-x-8">
                <a href="{% url 'products:home' %}"><li>Home</li></a>
                <a href="{% url 'Discussions:view_threads' %}"><li>Discussions</li></a>
                <a href="{% url 'BestDeals:best_deals' %}"><li>Best Deals</li></a>
            </ul>

            <div class="hidden md:flex items-center space-x-6 ml-12 relative">
                {% if user.is_authenticated %}
                    <a href="{% url 'WishList:view_wishlist' %}">
                        <img src="{% static 'images/wishicon.webp' %}" alt="My Wishlist" class="h-6 w-7">
                    </a>

                    <!-- Profile Icon with Dropdown -->
                    <div class="relative">
                        <button id="profileButton" class="focus:outline-none">
                            <img src="{% static 'images/profile.webp' %}" alt="My Profile" class="h-7 w-8">
                        </button>
                        <!-- Dropdown Menu -->
                        <div id="profileDropdown" class="hidden absolute right-0 mt-2 w-48 bg-white border border-gray-300 rounded-lg shadow-lg">
                            <div class="px-4 py-2">
                                <p class="text-gray-700 font-semibold">{{ user.username }}</p>
                                <p class="text-sm text-gray-500">Last login: {{ user.last_login|date:"Y-m-d H:i" }}</p>
                            </div>
                            <hr class="border-t border-gray-200">
                            <a href="{% url 'authentication:logout' %}" class="block px-4 py-2 text-red-600 hover:bg-gray-100">
                                Logout
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <a href="{% url 'authentication:login_page' %}" class="text-gray-700">Log In</a>
                    <a href="{% url 'authentication:register_page' %}" class="bg-[#B88E2F] hover:bg-amber-900 rounded-lg py-2 text-white px-4">Register</a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Mobile Menu -->
    <div id="mobileMenu" class="hidden md:hidden bg-[#F9F1E7] text-md text-gray-700 px-6 pt-4 pb-6">
        <ul class="flex flex-col items-center justify-center space-y-3 text-center">
            <li class="w-full">
                <a href="{% url 'products:home' %}" class="block hover:bg-white rounded-lg py-2">Home</a>
            </li>

            <li class="w-full">
                <a href="{% url 'Discussions:view_threads' %}" class="block hover:bg-white rounded-lg py-2">Discussions</a>
            </li>

            <li class="w-full">
                <a href="{% url 'BestDeals:best_deals' %}" class="block hover:bg-white rounded-lg py-2">Best Deals</a>
            </li>

            <li class="w-full">
                <a href="{% url 'WishList:view_wishlist' %}" class="block hover:bg-[#F9F1E7] rounded-lg py-2">Wish List</a>
            </li>
            {% if user.is_authenticated %}
                <li class="w-full">
                    <p class="text-gray-900">Last login: {{ user.last_login|date:"Y-m-d H:i" }}</p>
                </li>
                <li class="w-full">
                    <a href="{% url 'authentication:logout' %}" class="block bg-[#B88E2F] hover:bg-amber-900 rounded-lg py-2 text-white">Logout</a>
                </li>
            {% else %}
                <li class="w-full">
                    <a href="{% url 'authentication:login_page' %}" class="block bg-white rounded-lg py-2 hover:bg-gray-200">Log In</a>
                </li>
                <li class="w-full">
                    <a href="{% url 'authentication:register_page' %}" class="block bg-[#B88E2F] hover:bg-amber-900 rounded-lg py-2 text-white">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<script>
    var dropdownMenu = document.getElementById('dropdownMenu');
    var dropdownButton = document.getElementById('dropdownButton');
    var mobileMenu = document.getElementById('mobileMenu');
    var mobileMenuButton = document.getElementById('mobileMenuButton');
    var profileButton = document.getElementById('profileButton');
    var profileDropdown = document.getElementById('profileDropdown');

    dropdownButton?.addEventListener('click', function () {
        dropdownMenu.classList.toggle('hidden');
    });

    mobileMenuButton?.addEventListener('click', function () {
        mobileMenu.classList.toggle('hidden');
    });

    profileButton?.addEventListener('click', function (event) {
        event.stopPropagation();  // Prevent the click from closing the dropdown
        profileDropdown.classList.toggle('hidden');
    });

    // Close Dropdown
    window.onclick = function(event) {
        if (!dropdownButton?.contains(event.target)) {
            dropdownMenu.classList.add('hidden');
        }
        if (!mobileMenuButton?.contains(event.target) && !mobileMenu.contains(event.target)) {
            mobileMenu.classList.add('hidden');
        }
        if (!profileButton?.contains(event.target) && !profileDropdown.contains(event.target)) {
            profileDropdown.classList.add('hidden');
        }
    }
</script>